services:
  # instance zookeeper
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"
  # instance kafka
  broker:
    hostname: broker
    container_name: broker
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
        - "9092:9092"
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
  # database
  postgres:
    hostname: postgres
    container_name: postgres
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  # connector
  connect:
    container_name: connect
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - "8083:8083"
    links:
      - broker
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=broker:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  # kafka interface/painel
  kafka-painel:
    container_name: kafka-painel
    image: confluentinc/cp-enterprise-control-center:7.7.1
    ports:
      - "9021:9021"
    depends_on:
      - broker
      - connect
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1